/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clusterautodeploy;

import java.awt.Point;
import javax.swing.JOptionPane;

/**
 *
 * @author fahimeh
 */
public class UpdateFrame extends javax.swing.JFrame {

    
    private String ip_address;
    private String user_name;
    private String password;
    private boolean isSeedNode;
    private int index;
    private Point point;
    
    private CassandraSimulator previousJFrame;
    public void setPreviousJFrame(CassandraSimulator previousJFrame) {
        this.previousJFrame = previousJFrame;
    }
    /**
     * Creates new form UpdateFrame
     */
    public UpdateFrame(boolean isSeedNode, String ip_address, String user_name, String password, int index, Point point) {
        this.isSeedNode = isSeedNode;
        this.ip_address = ip_address;
        this.user_name = user_name;
        this.password = password;
        this.index = index;
        this.point = point;
        
        initComponents();
        
        this.jTextField1.setText(this.ip_address);
        this.jTextField2.setText(this.user_name);
        this.jPasswordField1.setText(this.password);
        this.jCheckBox1.setSelected(isSeedNode);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("ip_address:");

        jCheckBox1.setText("Seed Node?");

        jLabel2.setText("user_name:");

        jLabel3.setText("password:");

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jCheckBox1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jPasswordField1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jCheckBox1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (this.isSeedNode) {
            this.setVisible(false);
            this.previousJFrame.deleteSeedNodeFromTheCluster(index);
            this.previousJFrame.setEnabled(true);
        } else {
            this.setVisible(false);
            this.previousJFrame.deleteNormalNodeFromTheCluster(index);
            this.previousJFrame.setEnabled(true);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.previousJFrame.setUpdateJFrameToNull();
        this.previousJFrame.setEnabled(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (jTextField1.getText().equals("") || jTextField2.getText().equals("") || jPasswordField1.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "None of the boxes can be empty !!", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (this.isSeedNode == jCheckBox1.isSelected() && this.ip_address.equals(jTextField1.getText()) && this.user_name.equals(jTextField2.getText()) &&
                    this.password.equals(jPasswordField1.getText())) {
               JOptionPane.showMessageDialog(this, "You haven't updated any configuration information about the ndoe !!", "Error", JOptionPane.ERROR_MESSAGE);
            }
            else {
              if (this.isSeedNode && !this.jCheckBox1.isSelected()) {
                  this.setVisible(false);
                  this.previousJFrame.deleteSeedNodeFromTheCluster(index);
                  this.previousJFrame.addToThecluster(false, point, ip_address, user_name, password);
                  this.previousJFrame.setEnabled(true);
              } else if (!this.isSeedNode && this.jCheckBox1.isSelected()) {
                  this.setVisible(false);
                  this.previousJFrame.deleteNormalNodeFromTheCluster(index);
                  this.previousJFrame.addToThecluster(true, point, ip_address, user_name, password);
                  this.previousJFrame.setEnabled(true);
              } else if (this.isSeedNode && this.jCheckBox1.isSelected()) {
                  this.setVisible(false);
                  this.previousJFrame.deleteSeedNodeFromTheCluster(index);
                  this.previousJFrame.addToThecluster(true, point, ip_address, user_name, password);
                  this.previousJFrame.setEnabled(true);
              } else { // (!this.isSeedNode && !this.jCheckBox1.isSelected())
                  this.setVisible(false);
                  this.previousJFrame.deleteNormalNodeFromTheCluster(index);
                  this.previousJFrame.addToThecluster(false, point, ip_address, user_name, password);
                  this.previousJFrame.setEnabled(true);
              }
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
